version: '3'

services:
  server_app:
    image: node:latest # バージョン指定も可能 ex. node:12.16.1
    container_name: server_app
    tty: true
    volumes:
      - ./src:/src
    working_dir: "/src"
    networks:
      - server-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg5936
      POSTGRES_DB: db
    volumes:
      - ./db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - server-network
      
volumes:
  db_data:
      
networks:
    server-network:
        external: true