version: '3.3'

networks:
    server-network:
      name: node-server-network
      driver: bridge
      external: false
      ipam:
        driver: default
        config:
          - subnet: 172.27.0.0/24

services:
  node:
    build: ./node
    container_name: node
    tty: true
    volumes:
      - ./node:/app
    ports:
      - 3000:3000
    depends_on:
      - pg
    networks:
      server-network:
        ipv4_address: 172.27.0.3

  pg:
    build: ./pg
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg5936
      POSTGRES_DB: db
    volumes:
      - ./pg/db_data:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      server-network:
        ipv4_address: 172.27.0.2
      
volumes:
  data:
      