FROM node:alpine

#RUN mkdir node-server
WORKDIR /app

#COPY ./package.json ./package-lock.json /node-server/

#RUN npm install

#RUN mkdir src
#COPY ./src/* /node-server/src/

#CMD [ "node", "src/index.js" ]